#!/usr/bin/env python
#David Shinn
"""
ITS 3210 Introduction to Scripting Languages
Governor's State University
Student Name

Assignment 2

This program should receive input from the user from both the command line arguments
used when launching the script and by use of prompts while the script is running. The
comments in this assignment give further guidance on what specific input is expected
and how it is to be handled.

Feel free to be creative and go beyond the minimum requirements. The primary learning
objective of this assignment is receiving user input, both from command line arguments
and within the program's execution. Can you incorporate any previously learned knowledge
about Python into this exercise?
"""

from sys import argv

script_name, user_name, age = argv

###string variables substituted using %s 
print "Hello %s, you are at the very YOUNG age of %s years old!" % (user_name, age)  # display this in a friendlier way, e.g. "Hello {user_name}, you
                      # are at the very YOUNG age of {age} years old!"

print """The next two questions ask your height in feet and inches. If you are 5'11",
answer 5 to the first question and 11 to the second."""
height_feet = raw_input("How many feet tall are you (excluding inches)? ")
height_inches = raw_input("How many inches tall are you (excluding feet)? ")

###single ' and double " added using \ formatting
print "%s\'%s\"" % (height_feet, height_inches)  # display this in the format 5'10" for values 5 and 10

# calculate how many inches tall the user is based on their input
# for instance, if they enter 5 and 10, they are 70 inches tall

###string input converted to integer using int() method. Basic math calculates inches
inches = (int(height_feet) * 12) + int(height_inches)

###output using %d for integer
print "You are %d inches tall." % inches
